apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-balance-grpc
  namespace: test-g
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: go-balance-grpc
  template:
    metadata:
      labels:
        app: go-balance-grpc
        version: "go-balance-grpc"
    spec:
      containers:
      - name: go-balance-grpc
        imagePullPolicy: Never
        image: go_balance_grpc
        resources:
           requests:
             cpu: 250m
             memory: 100Mi
           limits:
             cpu: 500m
             memory: 200Mi
        ports:
        - containerPort: 50051
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051", "-rpc-header=jwt:cookie"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051", "-rpc-header=jwt:cookie"]
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
        - name: PORT
          value: "50051"
        - name: NAME_POD
          value: "pod-go-balance-grpc-08"
      terminationGracePeriodSeconds: 60
